### ISSUE TITLE
consider using organization definition in the affiliation property of person

### ISSUE THREAD

**Issue by fdiblen** [EVERSE-ResearchSoftware/schemas#11]
Organization can be used in the affiliation property of the person. This will improve the structure and reduce the complexity of the database schema.

**Comment by dgarijo** [comment]
But an organization can be responsible for an indicator, no? For example,
W3C, or an ISO working group

**Comment by fdiblen** [comment]
Sure, in that case we only use the affiliation property. We may need to change the name of `person` definition to something else.

Below is an example:

```yaml
...
authors:
   - 
     affiliation: Barcelona Supercomputing Center, Department of X
   - 
     name: Daniel Garijo
     affiliation: Universidad Politécnica de Madrid
contacts:
   - 
     affiliation: Barcelona Supercomputing Center, Department of X
 ```
